name: "📖 Documentation Change Request"
description: "Suggest improvements, corrections, or additions to the documentation"
title: "[Docs]: "
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!  
        Please fill out the details below so we can make updates faster.
        
  - type: dropdown
    id: type-of-change
    attributes:
      label: "Type of Documentation Change"
      options:
        - Fix typo or grammar
        - Update outdated content
        - Add missing content
        - Improve clarity or formatting
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: "Affected Page/Section"
      description: "Link to the page or file that needs an update (if applicable)"
      placeholder: "docs/installation.md or https://project/docs/installation"

  - type: textarea
    id: current
    attributes:
      label: "Current Content"
      description: "What does the documentation currently say?"
      placeholder: "Paste or summarize the current content here"

  - type: textarea
    id: suggested
    attributes:
      label: "Suggested Change"
      description: "What should it say instead? Suggest edits or improvements."
      placeholder: "Propose corrected text, examples, or explanation here"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any extra details, screenshots, or references"