name: Check Pipecat Version Sync

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sync:
    name: Verify Pipecat Versions Match
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Make scripts executable
        run: chmod +x scripts/*.sh
      
      - name: Check pipecat version synchronization
        run: ./scripts/check-pipecat-sync.sh